name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from Dependabot
        id: check
        run: echo "is_dependabot=$(jq -r .pull_request.user.login $GITHUB_EVENT_PATH | grep -q dependabot && echo true || echo false)" >> $GITHUB_ENV
        
      - name: Auto-approve Dependabot PR
        if: env.is_dependabot == 'true'
        run: gh pr review --approve "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Merge Dependabot PR
        if: env.is_dependabot == 'true'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
